/* Lifetime listening stats for the homepage #music section.
 *
 * Data comes from the stats.fm public REST API, which serves
 * `access-control-allow-origin: *` — so the browser reads it directly and the
 * site stays a pile of static files. No key, no proxy, no build step.
 *
 * Two endpoints, fetched in parallel:
 *   /streams/stats?range=lifetime   -> total streams, total ms, distinct counts
 *   /streams/stats/dates            -> hour-of-day buckets (the listening clock)
 *
 * If any of that fails — stats.fm down, a privacy toggle flipped off, a phone on
 * a bad connection — we fall back to SNAPSHOT below and label the section with
 * the capture date. Refresh the snapshot with ./refresh-music-snapshot.py.
 */

const STATSFM = {
  // stats.fm username or numeric id — the part after stats.fm/user/.
  // While this is REPLACE_ME the live fetch is skipped entirely.
  user: 'mredc',
  base: 'https://api.stats.fm/api/v1',
  // The clock shows when *I* listen, so it's pinned to my timezone rather than
  // the viewer's — otherwise the same chart tells a different story per reader.
  timeZone: 'Europe/London',
  timeoutMs: 6000,
};

/* Baked fallback. `null` means "never captured" — the section then hides itself
 * rather than rendering zeroes that would read as real numbers.
 * Generated by refresh-music-snapshot.py; don't hand-edit. */
const SNAPSHOT = {
  streams: 161917,
  durationMs: 27118117742,
  tracks: 17797,
  artists: 7071,
  albums: 12154,
  hours: [
    8516, 6445, 4017, 3407, 2664, 2066, 2023, 1494, 3575, 3700, 4882, 6147, 7266, 7479, 8543, 9232,
    9855, 10008, 8415, 8206, 9967, 11825, 11638, 10547,
  ],
  capturedAt: '2026-08-24',
};

/* ---------------------------------------------------------------- fetching */

async function getJSON(path) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), STATSFM.timeoutMs);
  try {
    const res = await fetch(`${STATSFM.base}/users/${STATSFM.user}${path}`, {
      signal: controller.signal,
    });
    if (!res.ok) throw new Error(`stats.fm ${res.status} on ${path}`);
    return (await res.json()).items;
  } finally {
    clearTimeout(timer);
  }
}

/* Normalises both the live payloads and the snapshot into one shape, so the
 * render path never has to know which one it got. */
function shape(stats, dates) {
  const hours = [];
  for (let h = 0; h < 24; h++) hours.push(dates?.hours?.[h]?.count ?? 0);

  return {
    streams: stats.count,
    durationMs: stats.durationMs,
    tracks: stats.cardinality?.tracks ?? 0,
    artists: stats.cardinality?.artists ?? 0,
    albums: stats.cardinality?.albums ?? 0,
    hours,
    capturedAt: null,
  };
}

async function loadLive() {
  const tz = encodeURIComponent(STATSFM.timeZone);
  const [stats, dates] = await Promise.all([
    getJSON('/streams/stats?range=lifetime'),
    getJSON(`/streams/stats/dates?timeZone=${tz}`),
  ]);
  return shape(stats, dates);
}

/* ------------------------------------------------------------- formatting */

const nf = new Intl.NumberFormat('en-GB');

function compact(n) {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 10_000) return `${Math.round(n / 1000)}K`;
  return nf.format(n);
}

function hourLabel(h) {
  return `${String(h).padStart(2, '0')}:00`;
}

function hourRange(h) {
  return `${hourLabel(h)}–${hourLabel((h + 1) % 24)}`;
}

/* ---------------------------------------------------------------- the clock */

// rLabel clears rOuter by enough that the peak spoke's thicker cap can't
// collide with the hour label sitting beyond it.
const CLOCK = { size: 400, cx: 200, cy: 200, rInner: 72, rOuter: 168, rLabel: 190 };

/* Hour 0 sits at the top and time runs clockwise, like a real clock face. */
function pointAt(hour, radius) {
  const theta = (hour / 24) * Math.PI * 2;
  return [CLOCK.cx + radius * Math.sin(theta), CLOCK.cy - radius * Math.cos(theta)];
}

function svgEl(name, attrs) {
  const el = document.createElementNS('http://www.w3.org/2000/svg', name);
  for (const [k, v] of Object.entries(attrs)) el.setAttribute(k, v);
  return el;
}

function renderClock(root, hours) {
  const svg = root.querySelector('.music-clock-svg');
  const caption = root.querySelector('.music-clock-peak-caption');
  const hourOut = root.querySelector('.music-clock-peak-hour');
  const countOut = root.querySelector('.music-clock-peak-count');
  const max = Math.max(...hours, 1);
  const span = CLOCK.rOuter - CLOCK.rInner;
  const peak = hours.indexOf(max);

  function showPeak() {
    caption.textContent = 'Peak';
    hourOut.textContent = hourRange(peak);
    countOut.textContent = `${nf.format(max)} streams`;
  }

  svg.setAttribute('viewBox', `0 0 ${CLOCK.size} ${CLOCK.size}`);
  svg.replaceChildren();

  // No concentric rings. Spokes sitting inside a set of faint circles read as
  // orbits rather than a clock; the hour labels alone give enough structure.
  // Labelled every three hours, which is what makes the ring of spokes scan as
  // a clock face without crowding it with 24 numbers.
  for (const h of [0, 3, 6, 9, 12, 15, 18, 21]) {
    const [x, y] = pointAt(h, CLOCK.rLabel);
    const label = svgEl('text', {
      x,
      y,
      class: 'music-clock-axis',
      'text-anchor': 'middle',
      'dominant-baseline': 'middle',
      // Same --h stagger as the spokes, so each label arrives with its hour.
      style: `--h: ${h}`,
    });
    label.textContent = hourLabel(h);
    svg.append(label);
  }

  // Emphasis, not a value ramp: every spoke shares one hue and only the peak
  // hour is brought forward.
  const spokes = hours.map((count, h) => {
    const [x1, y1] = pointAt(h, CLOCK.rInner);
    const [x2, y2] = pointAt(h, CLOCK.rInner + (count / max) * span);
    return svgEl('line', {
      x1,
      y1,
      x2,
      y2,
      class: `music-clock-spoke${h === peak ? ' is-peak' : ''}`,
      // pathLength normalises every spoke to 1 unit regardless of its real
      // length, so one stroke-dashoffset keyframe draws them all at the same
      // rate. --h is the hour, which CSS turns into the stagger delay.
      pathLength: 1,
      style: `--h: ${h}`,
    });
  });
  svg.append(...spokes);

  // Hit areas go in a second pass so every one of them sits above every spoke —
  // interleaving them would let a tall neighbour swallow a short hour's hover.
  // Each spans the full radius, so 04:00 is as easy to hit as midnight.
  hours.forEach((count, h) => {
    const [x1, y1] = pointAt(h, CLOCK.rInner);
    const [x2, y2] = pointAt(h, CLOCK.rOuter);
    const hit = svgEl('line', { x1, y1, x2, y2, class: 'music-clock-hit' });

    // The centre doubles as the readout. A floating tooltip would sit on top of
    // it for the short spokes, and overhang the viewport for 06:00 and 18:00 on
    // a phone; reading out in the middle has neither problem at any width.
    hit.addEventListener('pointerenter', () => {
      caption.textContent = 'This hour';
      hourOut.textContent = hourRange(h);
      countOut.textContent = `${nf.format(count)} streams`;
      svg.classList.add('is-hovered');
      spokes[h].classList.add('is-active');
    });
    hit.addEventListener('pointerleave', () => {
      showPeak();
      svg.classList.remove('is-hovered');
      spokes[h].classList.remove('is-active');
    });
    svg.append(hit);
  });

  svg.setAttribute(
    'aria-label',
    `Streams by hour of day. Busiest hour ${hourRange(peak)} with ${nf.format(max)} streams.`
  );

  showPeak();

  // Screen-reader-only (.sr-only on the wrapper): the chart carries no visible
  // table, but the numbers still need a non-visual route that isn't 24 focus stops.
  const tbody = root.querySelector('.music-table tbody');
  tbody.replaceChildren();
  hours.forEach((count, h) => {
    const tr = document.createElement('tr');
    const th = document.createElement('th');
    th.scope = 'row';
    th.textContent = hourRange(h);
    const td = document.createElement('td');
    td.textContent = nf.format(count);
    tr.append(th, td);
    tbody.append(tr);
  });
}

/* --------------------------------------------------------------- rendering */

function render(root, data) {
  const set = (sel, value) => {
    root.querySelector(sel).textContent = value;
  };

  set('.music-streams', nf.format(data.streams));
  set('.music-hours', compact(Math.round(data.durationMs / 3_600_000)));
  set('.music-tracks', compact(data.tracks));
  set('.music-artists', compact(data.artists));
  set('.music-albums-count', compact(data.albums));

  renderClock(root, data.hours);

  const stamp = root.querySelector('.music-stamp');
  if (data.capturedAt) {
    stamp.textContent = `snapshot · ${data.capturedAt}`;
    stamp.hidden = false;
  } else {
    stamp.hidden = true;
  }

  root.dataset.state = 'ready';
}

/* ------------------------------------------------------------------- init */

async function initMusic() {
  const root = document.getElementById('music');
  if (!root) return;

  let data = null;

  if (STATSFM.user !== 'REPLACE_ME') {
    try {
      data = await loadLive();
    } catch (err) {
      console.warn('stats.fm unavailable, falling back to snapshot:', err.message);
    }
  }

  if (!data && SNAPSHOT) data = { ...SNAPSHOT, capturedAt: SNAPSHOT.capturedAt };

  // Nothing live and nothing baked: drop the section rather than show an empty
  // shell or placeholder numbers a reader would take as real.
  if (!data) {
    root.remove();
    document.querySelector('.nav-menu a[href="#music"]')?.closest('li')?.remove();
    return;
  }

  render(root, data);
}

document.addEventListener('DOMContentLoaded', () => {
  initMusic();
});
